In [22]:
import numpy as np
from libemg.feature_extractor import FeatureExtractor
from libemg.utils import get_windows
import pandas as pd

In [30]:
df = pd.read_csv('EMG-data.csv')
print(df.shape)
df.head()

(4237907, 11)


time  channel1  channel2  channel3  channel4  channel5  channel6  channel7  \
0     1   0.00001  -0.00002  -0.00001  -0.00003   0.00000  -0.00001   0.00000   
1     5   0.00001  -0.00002  -0.00001  -0.00003   0.00000  -0.00001   0.00000   
2     6  -0.00001   0.00001   0.00002   0.00000   0.00001  -0.00002  -0.00001   
3     7  -0.00001   0.00001   0.00002   0.00000   0.00001  -0.00002  -0.00001   
4     8  -0.00001   0.00001   0.00002   0.00000   0.00001  -0.00002  -0.00001   

   channel8  class  label  
0  -0.00001      0      1  
1  -0.00001      0      1  
2   0.00001      0      1  
3   0.00001      0      1  
4   0.00001      0      1

In [23]:
# Load data from a csv file:
data = np.loadtxt("emg_data.csv", delimiter=",")
data
# Split the raw EMG into windows
windows = get_windows(data, 50, 25)

In [8]:
fe = FeatureExtractor()
fe.get_feature_list()

['MAV',
 'ZC',
 'SSC',
 'WL',
 'LS',
 'MFL',
 'MSR',
 'WAMP',
 'RMS',
 'IAV',
 'DASDV',
 'VAR',
 'M0',
 'M2',
 'M4',
 'SPARSI',
 'IRF',
 'WLF',
 'AR',
 'CC',
 'LD',
 'MAVFD',
 'MAVSLP',
 'MDF',
 'MNF',
 'MNP',
 'MPK',
 'SKEW',
 'KURT',
 'RMSPHASOR',
 'PAP',
 'WLPHASOR',
 'MZP',
 'TM',
 'SM',
 'SAMPEN',
 'FUZZYEN',
 'DFTR',
 'ISD',
 'COR',
 'MDIFF',
 'MLK',
 'ACT',
 'MOB',
 'COMP',
 'WENG',
 'WV',
 'WWL',
 'WENT']

In [19]:
# Extract a list of features
feature_list = ['MAV', 'SSC', 'ZC', 'WL']
features_1 = fe.extract_features(feature_list, windows)

In [31]:
features_1['MAV']

array([[3.266000e+01, 1.300000e-05, 1.820000e-05, ..., 6.200000e-06,
        0.000000e+00, 1.000000e+00],
       [6.334000e+01, 1.160000e-05, 4.800000e-05, ..., 1.040000e-05,
        0.000000e+00, 1.000000e+00],
       [9.062000e+01, 1.060000e-05, 3.880000e-05, ..., 1.260000e-05,
        0.000000e+00, 1.000000e+00],
       ...,
       [5.313080e+04, 1.060000e-05, 4.120000e-05, ..., 2.300000e-05,
        4.000000e+00, 9.000000e+00],
       [5.315638e+04, 6.200000e-06, 3.300000e-05, ..., 1.600000e-05,
        4.000000e+00, 9.000000e+00],
       [5.318190e+04, 1.420000e-05, 2.340000e-05, ..., 1.440000e-05,
        4.000000e+00, 9.000000e+00]])

In [32]:
features_1['SSC']

array([[ 0, 47, 48, ..., 48, 48, 48],
       [ 0, 47, 48, ..., 48, 48, 48],
       [ 0, 48, 48, ..., 48, 48, 48],
       ...,
       [ 0, 48, 48, ..., 48, 48, 48],
       [ 0, 48, 48, ..., 48, 48, 48],
       [ 0, 48, 48, ..., 48, 48, 48]])

In [33]:
# Extract a predefined feature group
features_2 = fe.extract_feature_group('HTD', windows)

In [35]:
features_2['MAV']

array([[3.266000e+01, 1.300000e-05, 1.820000e-05, ..., 6.200000e-06,
        0.000000e+00, 1.000000e+00],
       [6.334000e+01, 1.160000e-05, 4.800000e-05, ..., 1.040000e-05,
        0.000000e+00, 1.000000e+00],
       [9.062000e+01, 1.060000e-05, 3.880000e-05, ..., 1.260000e-05,
        0.000000e+00, 1.000000e+00],
       ...,
       [5.313080e+04, 1.060000e-05, 4.120000e-05, ..., 2.300000e-05,
        4.000000e+00, 9.000000e+00],
       [5.315638e+04, 6.200000e-06, 3.300000e-05, ..., 1.600000e-05,
        4.000000e+00, 9.000000e+00],
       [5.318190e+04, 1.420000e-05, 2.340000e-05, ..., 1.440000e-05,
        4.000000e+00, 9.000000e+00]])

In [36]:
features_2['SSC']

array([[ 0, 47, 48, ..., 48, 48, 48],
       [ 0, 47, 48, ..., 48, 48, 48],
       [ 0, 48, 48, ..., 48, 48, 48],
       ...,
       [ 0, 48, 48, ..., 48, 48, 48],
       [ 0, 48, 48, ..., 48, 48, 48],
       [ 0, 48, 48, ..., 48, 48, 48]])